[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@account-abstraction=lib/account-abstraction",
  "@era-contracts=lib/foundry-era-contracts"
]

# Enable via-ir compilation to fix "Stack too deep" errors
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
